# Stage 1
FROM node:14-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
RUN npm install -g @angular/cli
COPY . /app
EXPOSE 4200
CMD ["ng", "serve", "--host","0.0.0.0", "--port", "4200"]
